version: '3'

services:
  monitorr:
    image: monitorr/monitorr:latest # should be 1.7.6m as the docker build as been abandonned
    container_name: monitorr-poc
    ports:
      - '127.0.0.1:7000:80'
    volumes:
      - type: volume
        source: monitorr
        target: /app
        read_only: false
    environment:
      - TZ=Europe/Paris
      - PGID=1000
      - PUID=1000

volumes:
  monitorr: